# -*- coding: utf-8 -*-
#
# This file is part of COUNTER-Robots.
# Copyright (C) 2018-2025 CERN.
#
# COUNTER-Robots is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Small script to update the bundled robot, machine and AI-crawler lists.

Usage:

.. code-block:: console

    $ cd scripts
    $ python update-lists.py
"""

import json
import re
from os.path import dirname, join

try:
    from urllib.request import urlopen
except ImportError:
    from urllib import urlopen


files = [
    (
        "machine.txt",
        "https://raw.githubusercontent.com/CDLUC3/Make-Data-Count/"
        "master/user-agents/lists/machine.txt",
    ),
    (
        "robot.txt",
        "https://raw.githubusercontent.com/atmire/COUNTER-Robots/"
        "master/generated/COUNTER_Robots_list.txt",
    ),
]

AI_ROBOTS_URL = (
    "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json"
)


def _get_package_path(filename):
    """Retrieve path of a file in this Python package."""
    return join(dirname(__file__), "../counter_robots/data/", filename)


def update_file(url, filename):
    """Update the content of a single file."""
    resp = urlopen(url)
    if resp.code != 200:
        raise Exception("GET {} failed.".format(url))
    with open(_get_package_path(filename), "w") as fp:
        for l in resp:
            if not l.startswith(b"#"):
                fp.write(l.decode("utf8"))
    print("Updated {}".format(filename))


def update_ai_robots():
    """Update the AI crawler list from ai-robots-txt/ai.robots.txt.

    The upstream is a JSON object keyed by bot name; the names are written one per
    line, regex-escaped so they match literally.
    """
    resp = urlopen(AI_ROBOTS_URL)
    if resp.code != 200:
        raise Exception("GET {} failed.".format(AI_ROBOTS_URL))
    names = sorted(json.loads(resp.read().decode("utf8")), key=str.lower)
    header = (
        "# AI crawler/scraper user agents, one regex-escaped name per line.\n"
        "# GENERATED by scripts/update-lists.py from ai-robots-txt/ai.robots.txt (MIT).\n"
        "# Loaded by extended_preset as robots, matched case-insensitively.\n"
    )
    with open(_get_package_path("ai_robots.txt"), "w") as fp:
        fp.write(header)
        fp.write("\n".join(re.escape(name) for name in names))
        fp.write("\n")
    print("Updated ai_robots.txt ({} entries)".format(len(names)))


def main():
    """Update the files containing the list of robots and machines."""
    for filename, url in files:
        update_file(url, filename)
    update_ai_robots()


if __name__ == "__main__":
    main()
