# -*- coding: utf-8 -*-
#
# This file is part of COUNTER-Robots.
# Copyright (C) 2025 CERN.
#
# COUNTER-Robots is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Regenerate the datacenter ASN list from external sources.

Writes ``counter_robots/data/datacenter_asn.txt`` from the union of:

- brianhama/bad-asn-list (hosting/datacenter ASNs), and
- PeeringDB networks registered with ``info_type`` of ``Content``.

Both are fetched anonymously in a single request each. The hand-maintained
``datacenter_asn_allow.txt`` is left untouched.

Usage:

.. code-block:: console

    $ cd scripts
    $ python update-asn-list.py
"""

import csv
import io
import json
from os.path import dirname, join
from urllib.request import urlopen

BAD_ASN_URL = (
    "https://raw.githubusercontent.com/brianhama/bad-asn-list/master/bad-asn-list.csv"
)
PEERINGDB_URL = "https://www.peeringdb.com/api/net?depth=0"
PEERINGDB_TYPES = {"Content"}


def _data_path(filename):
    return join(dirname(__file__), "../counter_robots/data/", filename)


def _fetch(url):
    resp = urlopen(url)
    if resp.code != 200:
        raise Exception("GET {} failed ({}).".format(url, resp.code))
    return resp.read()


def _bad_asns():
    reader = csv.reader(io.StringIO(_fetch(BAD_ASN_URL).decode("utf-8")))
    next(reader, None)  # header
    return {int(row[0]) for row in reader if row and row[0].strip().isdigit()}


def _peeringdb_asns():
    data = json.loads(_fetch(PEERINGDB_URL).decode("utf-8"))["data"]
    return {
        int(n["asn"])
        for n in data
        if n.get("asn") and n.get("info_type") in PEERINGDB_TYPES
    }


def main():
    """Regenerate the datacenter ASN list."""
    asns = sorted(_bad_asns() | _peeringdb_asns())
    header = (
        "# Datacenter / hosting ASNs. GENERATED by scripts/update-asn-list.py from the\n"
        "# union of brianhama/bad-asn-list and PeeringDB networks of type 'Content'.\n"
        "# One ASN per line. Do not edit by hand; exemptions go in datacenter_asn_allow.txt.\n"
    )
    with open(_data_path("datacenter_asn.txt"), "w") as fp:
        fp.write(header)
        fp.write("\n".join(str(asn) for asn in asns))
        fp.write("\n")
    print("Updated datacenter_asn.txt ({} ASNs)".format(len(asns)))


if __name__ == "__main__":
    main()
