# -*- coding: utf-8 -*-
#
# This file is part of COUNTER-Robots.
# Copyright (C) 2025 CERN.
#
# COUNTER-Robots is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Regenerate the datacenter ASN list from external sources.

Writes ``counter_robots/data/datacenter_asn.txt`` from the union of:

- brianhama/bad-asn-list (hosting/datacenter ASNs),
- PeeringDB networks registered with ``info_type`` of ``Content``, and
- O-X-L/open-bot-list ASNs categorized as hosting, cloud or cdn, minus any the
  same source also lists under isp or education. The other categories carry human
  traffic, so they are skipped.

All are fetched anonymously. The hand-maintained ``datacenter_asn_allow.txt`` is
left untouched.

Usage:

.. code-block:: console

    $ cd scripts
    $ python update-asn-list.py
"""

import csv
import io
import json
from os.path import dirname, join
from urllib.request import urlopen

BAD_ASN_URL = (
    "https://raw.githubusercontent.com/brianhama/bad-asn-list/master/bad-asn-list.csv"
)
PEERINGDB_URL = "https://www.peeringdb.com/api/net?depth=0"
PEERINGDB_TYPES = {"Content"}

# O-X-L/open-bot-list (BSD-3-Clause, (c) OXL IT Services). Datacenter categories only.
OPEN_BOT_LIST_BASE = (
    "https://raw.githubusercontent.com/O-X-L/open-bot-list/latest/matches/asn"
)
OPEN_BOT_LIST_CATEGORIES = ("hosting", "cloud", "cdn")
# open-bot-list occasionally files one ASN under both a datacenter and a human
# category; these are subtracted so a consumer ISP is never flagged as datacenter.
OPEN_BOT_LIST_HUMAN_CATEGORIES = ("isp", "education")


def _data_path(filename):
    return join(dirname(__file__), "../counter_robots/data/", filename)


def _fetch(url):
    resp = urlopen(url)
    if resp.code != 200:
        raise Exception("GET {} failed ({}).".format(url, resp.code))
    return resp.read()


def _bad_asns():
    reader = csv.reader(io.StringIO(_fetch(BAD_ASN_URL).decode("utf-8")))
    next(reader, None)  # header
    return {int(row[0]) for row in reader if row and row[0].strip().isdigit()}


def _peeringdb_asns():
    data = json.loads(_fetch(PEERINGDB_URL).decode("utf-8"))["data"]
    return {
        int(n["asn"])
        for n in data
        if n.get("asn") and n.get("info_type") in PEERINGDB_TYPES
    }


def _open_bot_list_category(category):
    reader = csv.DictReader(
        io.StringIO(
            _fetch("{}/{}.csv".format(OPEN_BOT_LIST_BASE, category)).decode("utf-8")
        )
    )
    asns = set()
    for row in reader:
        # The asn cell may pipe-delimit several ASNs for one organization.
        for part in (row.get("asn") or "").split("|"):
            if part.strip().isdigit():
                asns.add(int(part.strip()))
    return asns


def _open_bot_list_asns():
    datacenter = set().union(
        *(_open_bot_list_category(c) for c in OPEN_BOT_LIST_CATEGORIES)
    )
    human = set().union(
        *(_open_bot_list_category(c) for c in OPEN_BOT_LIST_HUMAN_CATEGORIES)
    )
    return datacenter - human


def main():
    """Regenerate the datacenter ASN list."""
    asns = sorted(_bad_asns() | _peeringdb_asns() | _open_bot_list_asns())
    header = (
        "# Datacenter / hosting ASNs. GENERATED by scripts/update-asn-list.py from the union of:\n"
        "#   - brianhama/bad-asn-list\n"
        "#   - PeeringDB networks of type 'Content'\n"
        "#   - O-X-L/open-bot-list hosting/cloud/cdn (BSD-3-Clause, (c) OXL IT Services)\n"
        "# One ASN per line. Do not edit by hand; exemptions go in datacenter_asn_allow.txt.\n"
    )
    with open(_data_path("datacenter_asn.txt"), "w") as fp:
        fp.write(header)
        fp.write("\n".join(str(asn) for asn in asns))
        fp.write("\n")
    print("Updated datacenter_asn.txt ({} ASNs)".format(len(asns)))


if __name__ == "__main__":
    main()
